- Handle spaces in paths better (IDL path, directory, save file).

diff --git a/bin/cubism_vm b/bin/cubism_vm
--- a/bin/cubism_vm
+++ b/bin/cubism_vm
@@ -2,8 +2,8 @@
 # Run the binary cubism IDL save file
 
 top=$(dirname "$0")
-cubism_vm=$top/cubism_vm.sav
-[ -f $cubism_vm ] || { echo "Cannot find Cubism save file"; exit 1; }
+cubism_vm="$top/cubism_vm.sav"
+[ -f "$cubism_vm" ] || { echo "Cannot find Cubism save file"; exit 1; }
 
 if [ -z "$IDL_DIR" ]; then
     if [ -d /usr/local/rsi/idl ]; then
@@ -16,13 +16,14 @@ if [ -z "$IDL_DIR" ]; then
     fi
 fi
 
-IDL=$IDL_DIR/bin/idl
+IDL="$IDL_DIR/bin/idl"
 
-# Handle spaces in the directories, by encoding as form feeds
-dir=$(echo $HOME | tr ' ' '\014')
+# Handle spaces in the directories, by encoding as form feeds (since
+# IDL -arg can't handle spaces)  Undo in cubism_vm.pro
+dir=$(echo "$HOME" | tr ' ' '\014')
 if [ $# -ge 1 ]; then 
-    file=$(echo $1 | tr ' ' '\014')
-    $IDL -vm=$cubism_vm -arg "$dir" -arg "$file"
+    file=$(echo "$1" | tr ' ' '\014')
+    "$IDL" -vm="$cubism_vm" -arg "$dir" -arg "$file"
 else
-    $IDL -vm=$cubism_vm -arg "$dir"
+    "$IDL" -vm="$cubism_vm" -arg "$dir"
 fi
